### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by ryonakano** [comment]
@Vistaus I suppose your PR should be merged once these conflicts are fixed.

**Comment by Vistaus** [comment]
I don't know what's wrong with those files. There clearly is a conflict, but what did I do wrong?

**Comment by ryonakano** [comment]
There should be no conflicts when you created this PR, but as other contributors create their PRs and their PRs are merged, those conflicts may be occurred.

I think there should be a button like "Resolve conflicts" next to "This branch has conflicts that must be resolved". Clicking this button and changing the contents of these conflicting files to the following should fix these conflicts:

```
fr
lt
nl
ru
```

**Comment by Vistaus** [comment]
Thanks, I resolved it now :)

**Comment by bernardodsanderson** [comment]
Thanks @Vistaus and @ryonakano!

**Pull request merged**
